### PR TITLE
Fix attachPermission instanceof error

### LINKED ISSUE #139: Fails to attachPermission with error 'The specified permissions is not a supported.'
This code inside `permission.js` is flawed:
```
  else if (permission instanceof iam.PolicyStatement) {
    role.addToPolicy(permission);
  }
```
This check fails if the `iam` modules imported by SST and by user are not the same module. Ie. one version of `@aws-cdk/aws-iam` found inside `node_modules`, and one version found inside `node_modules/@serverless-stack/serverless-stack/node_modules/@aws-cdk/aws-iam`.

Could check `permission.constructor.name`, but even that is not perfect.

### PR DESCRIPTION
**Pull request by jayair**
Closes #139

@fwang Review the changes

### CODE REVIEW

File: packages/resources/src/util/permission.ts [hunk 1]
```diff
@@ -104,6 +115,7 @@ export function attachPermissionsToRole(
       }
       // Case: grant method
       else if (
+        Array.isArray(permission) &&
         permission.length === 2 &&
         permission[0] instanceof cdk.Construct &&
```
Comment (fwang) [inline packages/resources/src/util/permission.ts:120]: @jayair This `instanceof` needs to be changed as well
